#!/usr/bin/env python3
"""Generate LaTeX tables for VLM experiment results.

Reads zeroshot_all_metrics.json and fewshot_all_metrics.json,
produces LaTeX tables for the TCSVT 2026 paper.

Three tables are generated:
  1. Zero-Shot VLM Baseline Comparison (Table I)
  2. VLM Scaling Behavior: ZS → FS → LoRA (Table II)
  3. Supplementary: Full Few-Shot Results
"""

import json
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = PROJECT_ROOT / "outputs"
TABLE_DIR = OUTPUT_DIR / "tables"
TABLE_DIR.mkdir(parents=True, exist_ok=True)

# Metric display names for table headers
METRIC_NAMES = {
    "BLEU_1": r"B@1",
    "BLEU_2": r"B@2",
    "BLEU_3": r"B@3",
    "BLEU_4": r"B@4",
    "METEOR": r"M",
    "ROUGE_L": r"R",
    "CIDER": r"C",
    "SPICE": r"S",
    "S_m": r"$S_m$",
    "S*_m": r"$S^*_m$",
    "CLIPScore": r"CLIP-S",
    "RefCLIPScore": r"RefCLIP-S",
    "RefMax": r"RefMax",
}

# Models in display order for zero-shot table
ZEROSHOT_MODEL_ORDER = [
    ("blip2", "BLIP-2", "VLM (ZS)"),
    ("instructblip", "InstructBLIP", "VLM (ZS)"),
    ("llava", "LLaVA-1.5-7B", "VLM (ZS)"),
    ("qwen3vl", "Qwen3-VL-8B", "VLM (ZS)"),
    ("internvl35", "InternVL3.5-8B", "VLM (ZS)"),
]

# LoRA models
LORA_MODELS = [
    ("llava-lora", "LLaVA-1.5-7B", "LoRA"),
    ("qwen3vl-lora", "Qwen3-VL-8B", "LoRA"),
    ("internvl35-lora", "InternVL3.5-8B", "LoRA"),
]

# Models for scaling table (ZS, FS k=1, FS k=3, LoRA)
SCALING_MODELS = [
    ("llava", "LLaVA-1.5-7B"),
    ("qwen3vl", "Qwen3-VL-8B"),
    ("internvl35", "InternVL3.5-8B"),
]

# Metrics for Table I (detailed BLEU 1-4 breakdown)
TABLE_I_METRICS = ["BLEU_1", "BLEU_2", "BLEU_3", "BLEU_4", "METEOR", "ROUGE_L", "CIDER", "SPICE", "S*_m", "S_m"]
# Metrics included in main tables (Tables II, combined)
MAIN_METRICS = ["BLEU_4", "METEOR", "ROUGE_L", "CIDER", "SPICE", "S_m", "CLIPScore"]
# Metrics for supplementary tables
SUPP_METRICS = ["BLEU_4", "METEOR", "ROUGE_L", "CIDER", "SPICE", "S_m", "CLIPScore", "RefCLIPScore"]
# All metrics available in the JSON files (for Table II: full detail)
ALL_METRICS = ["BLEU_1", "BLEU_2", "BLEU_3", "BLEU_4", "METEOR", "ROUGE_L", "CIDER", "SPICE", "S*_m", "S_m", "CLIPScore", "RefCLIPScore", "RefMax"]
# Metrics for Table II (scaling): semantic composite + ref-free only
TABLE_II_METRICS = ["BLEU_4", "S_m", "S*_m", "CLIPScore", "RefCLIPScore"]


def load_json(path):
    with open(path) as f:
        return json.load(f)


def fmt_val(val, metric_key):
    """Format a metric value with appropriate precision."""
    if val is None:
        return "--"
    if metric_key in ("CLIPScore", "RefCLIPScore", "RefMax"):
        # Multiply by 100 for percentage display
        return f"{val * 100:.1f}"
    elif metric_key in ("BLEU_1", "BLEU_2", "BLEU_3", "BLEU_4"):
        return f"{val:.2f}"
    elif metric_key in ("METEOR", "ROUGE_L", "SPICE", "S_m", "S*_m"):
        return f"{val:.2f}"
    elif metric_key in ("CIDER",):
        return f"{val:.2f}"
    return f"{val:.2f}"


def get_zs_data(data, model_key):
    """Get zero-shot data for a model."""
    return data.get(f"{model_key}/A", None)


def get_fs_data(fs_data, model_key, k):
    """Get few-shot data for a model and k value."""
    return fs_data.get(f"{model_key}/k={k}", None)


def generate_table_i(zeroshot_data):
    """Generate Table I: Zero-Shot VLM Baseline Comparison."""
    metrics = TABLE_I_METRICS
    n_cols = 1 + len(metrics)  # Methods + metrics

    header = r"""% Table I: Zero-Shot VLM Baseline Comparison on UICO Captioning
% Generated by scripts/generate_latex_tables.py
\begin{table}[t]
\centering
\caption{Comparison of VLM baselines on UICO urban incivility captioning (zero-shot, Prompt A).
All metrics computed against 5 reference captions per image (3500 test images).
$S_m$ is the composite score: mean of B@4, METEOR, ROUGE-L, CIDEr, and SPICE.
$S^*_m$ includes CLIPScore in the composite.}
\label{tab:vlm_zeroshot}
\small
\begin{tabular}{@{}l
"""

    # Column specs
    header += "c" * len(metrics)  # metrics columns
    header += "@{}}\n\\toprule\n"

    # Header row
    header += r"Methods "
    for m in metrics:
        header += f"& {METRIC_NAMES[m]} "
    header += r"\\" + "\n\\midrule\n"

    rows = []
    for model_key, display_name, model_type in ZEROSHOT_MODEL_ORDER:
        d = get_zs_data(zeroshot_data, model_key)
        if d is None:
            continue
        row = f"{display_name} ({model_type})"
        for m in metrics:
            val = d.get(m, None)
            row += f" & {fmt_val(val, m)}"
        row += r" \\"
        rows.append(row)

    # Add LoRA results (in separate section)
    rows.append(r"\midrule")
    rows.append(r"\multicolumn{" + str(n_cols) + r"}{c}{\textit{LoRA Fine-Tuned}} \\")
    rows.append(r"\midrule")

    for model_key, display_name, model_type in LORA_MODELS:
        d = get_zs_data(zeroshot_data, model_key)
        if d is None:
            continue
        row = f"{display_name} ({model_type})"
        for m in metrics:
            val = d.get(m, None)
            row += f" & {fmt_val(val, m)}"
        row += r" \\"
        rows.append(row)

    # Specialist placeholder (matching strategy doc draft)
    rows.append(r"\midrule")
    rows.append(r"\multicolumn{" + str(n_cols) + r"}{c}{\textit{Specialist Models (from prior work)}} \\")
    rows.append(r"\midrule")
    rows.append(r"UIFormer (CVPR'24) & 32.93 & -- & -- & 24.99 & -- & -- & 126.59 & 20.59 & -- & 50.35 \\")
    rows.append(r"AoANet & -- & -- & -- & -- & -- & -- & -- & -- & -- & -- \\")
    rows.append(r"Transformer & -- & -- & -- & -- & -- & -- & -- & -- & -- & -- \\")

    footer = r"""\bottomrule
\end{tabular}
\end{table}
"""
    return header + "\n".join(rows) + "\n" + footer


def generate_table_ii(zeroshot_data, fewshot_data):
    """Generate Table II: VLM Scaling Behavior (ZS → FS → LoRA)."""
    metrics = TABLE_II_METRICS
    settings = [
        ("Zero-Shot", "ZS"),
        ("Few-Shot ($k{=}1$)", "FS-k1"),
        ("Few-Shot ($k{=}3$)", "FS-k3"),
        ("LoRA", "LoRA"),
    ]

    header = r"""% Table II: VLM Scaling Behavior
% Generated by scripts/generate_latex_tables.py
\begin{table}[t]
\centering
\caption{VLM scaling behavior on UICO captioning: zero-shot $\to$ few-shot $\to$ LoRA fine-tuning.
All results on Prompt A with 3500 test images. $S_m$ is the composite score (mean of B@4, METEOR, ROUGE-L, CIDEr, SPICE);
$S^*_m$ additionally incorporates CLIPScore. CLIP-S and RefCLIP-S reported as $\times 100$ for readability.}
\label{tab:vlm_scaling}
\small
\begin{tabular}{@{}l
"""

    # Column specs (single label column + metrics)
    header += "c" * len(metrics)
    header += "@{}}\n\\toprule\n"

    # Header (no column title for the merged label column)
    header += r"& "
    for m in metrics:
        header += f"{METRIC_NAMES[m]} "
        if m != metrics[-1]:
            header += "& "
    header += r"\\" + "\n\\midrule\n"

    rows = []
    for model_key, display_name in SCALING_MODELS:
        first_row = True
        for setting_label, setting_key in settings:
            if setting_key == "ZS":
                d = get_zs_data(zeroshot_data, model_key)
            elif setting_key == "LoRA":
                d = get_zs_data(zeroshot_data, f"{model_key}-lora")
            elif setting_key == "FS-k1":
                d = get_fs_data(fewshot_data, model_key, 1)
            elif setting_key == "FS-k3":
                d = get_fs_data(fewshot_data, model_key, 3)
            else:
                d = None

            if d is None:
                continue

            if first_row:
                n_settings = sum(1 for s in settings if (
                    (s[1] == "ZS" and get_zs_data(zeroshot_data, model_key)) or
                    (s[1] == "LoRA" and get_zs_data(zeroshot_data, f"{model_key}-lora")) or
                    (s[1].startswith("FS") and get_fs_data(fewshot_data, model_key, int(s[1].split("-k")[1])))
                ))
                row = f"\\multirow{{{n_settings}}}{{*}}{{{display_name}}} {setting_label}"
                first_row = False
            else:
                padding = " " * (len(display_name) + 1)
                row = f"{padding}{setting_label}"

            for m in metrics:
                val = d.get(m, None)
                row += f" & {fmt_val(val, m)}"
            row += r" \\"
            rows.append(row)
        rows.append(r"\midrule")

    # Remove last \midrule
    if rows:
        rows.pop()

    footer = r"""\bottomrule
\end{tabular}
\end{table}
"""
    return header + "\n".join(rows) + "\n" + footer


def generate_table_supp_fewshot(fewshot_data):
    """Generate Supplementary Table: Full Few-Shot Results."""
    metrics = SUPP_METRICS
    fs_models = [
        ("llava", "LLaVA-1.5-7B"),
        ("qwen3vl", "Qwen3-VL-8B"),
        ("internvl35", "InternVL3.5-8B"),
    ]
    k_values = [1, 3]

    header = r"""% Supplementary Table S1: Few-Shot Detailed Results
% Generated by scripts/generate_latex_tables.py
\begin{table}[t]
\centering
\caption{Detailed few-shot captioning results on UICO (Prompt A, 3500 test images).
Examples sampled from training set with seed 42. $S^*_m$ includes CLIPScore in the composite.
CLIP-S and RefCLIP-S reported as $\times 100$ for readability.}
\label{tab:supp_fewshot}
\small
\begin{tabular}{@{}ll
"""

    header += "c" * len(metrics)
    header += "@{}}\n\\toprule\n"

    header += r"Model & $k$ "
    for m in metrics:
        header += f"& {METRIC_NAMES[m]} "
    header += r"\\" + "\n\\midrule\n"

    rows = []
    for model_key, display_name in fs_models:
        first_row = True
        for k in k_values:
            d = get_fs_data(fewshot_data, model_key, k)
            if d is None:
                continue
            if first_row:
                row = f"\\multirow{{{len(k_values)}}}{{*}}{{{display_name}}} & {k}"
                first_row = False
            else:
                row = f" & {k}"
            for m in metrics:
                val = d.get(m, None)
                row += f" & {fmt_val(val, m)}"
            row += r" \\"
            rows.append(row)
        rows.append(r"\midrule")

    if rows:
        rows.pop()

    footer = r"""\bottomrule
\end{tabular}
\end{table}
"""
    return header + "\n".join(rows) + "\n" + footer


def generate_combined_table(zeroshot_data, fewshot_data):
    """Generate a unified combined table with ZS + FS + LoRA for all models.

    This is an alternative compact format useful as the main results table.
    """
    metrics = MAIN_METRICS
    all_models = [
        ("BLIP-2", "blip2", True, False, False),       # (display, key, has_zs, has_fs, has_lora)
        ("InstructBLIP", "instructblip", True, False, False),
        ("LLaVA-1.5-7B", "llava", True, True, True),
        ("Qwen3-VL-8B", "qwen3vl", True, True, True),
        ("InternVL3.5-8B", "internvl35", True, True, True),
    ]

    header = r"""% Combined Table: VLM Results Summary
% Generated by scripts/generate_latex_tables.py
\begin{table*}[t]
\centering
\caption{Comprehensive VLM evaluation on UICO urban incivility captioning.
ZS = zero-shot; FS-1/FS-3 = few-shot with $k=1,3$ examples; LoRA = QLoRA fine-tuned.
Prompt A used for all settings. $S_m$ = mean of B@4, METEOR, ROUGE-L, CIDEr, SPICE.
CLIP-S reported as $\times 100$.}
\label{tab:vlm_combined}
\small
\begin{tabular}{@{}lll
"""

    header += "c" * len(metrics)
    header += "@{}}\n\\toprule\n"

    header += r"Model & Setting & Year "
    for m in metrics:
        header += f"& {METRIC_NAMES[m]} "
    header += r"\\" + "\n\\midrule\n"

    model_years = {
        "blip2": "2023",
        "instructblip": "2023",
        "llava": "2024",
        "qwen3vl": "2025",
        "internvl35": "2025",
    }

    rows = []
    for display_name, model_key, has_zs, has_fs, has_lora in all_models:
        n_rows = sum([has_zs, has_fs, has_fs, has_lora])  # fs contributes 2 rows (k=1,3)
        # Actually: has_zs (1) + has_fs (2 rows: k=1,k=3) + has_lora (1)
        n_rows = (1 if has_zs else 0) + (2 if has_fs else 0) + (1 if has_lora else 0)
        year = model_years.get(model_key, "--")
        first_row = True
        rows_this_model = 0

        # Zero-Shot row
        if has_zs:
            d = get_zs_data(zeroshot_data, model_key)
            if d:
                if first_row:
                    row = f"\\multirow{{{n_rows}}}{{*}}{{{display_name}}} & ZS & {year}"
                    first_row = False
                else:
                    row = f" & ZS & {year}"
                for m in metrics:
                    row += f" & {fmt_val(d.get(m), m)}"
                row += r" \\"
                rows.append(row)
                rows_this_model += 1

        # Few-Shot rows
        if has_fs:
            for k in [1, 3]:
                d = get_fs_data(fewshot_data, model_key, k)
                if d:
                    if first_row:
                        row = f"\\multirow{{{n_rows}}}{{*}}{{{display_name}}} & FS-{k} & {year}"
                        first_row = False
                    else:
                        row = f" & FS-{k} & {year}"
                    for m in metrics:
                        row += f" & {fmt_val(d.get(m), m)}"
                    row += r" \\"
                    rows.append(row)
                    rows_this_model += 1

        # LoRA row
        if has_lora:
            d = get_zs_data(zeroshot_data, f"{model_key}-lora")
            if d:
                if first_row:
                    row = f"\\multirow{{{n_rows}}}{{*}}{{{display_name}}} & LoRA & {year}"
                    first_row = False
                else:
                    row = f" & LoRA & {year}"
                for m in metrics:
                    row += f" & {fmt_val(d.get(m), m)}"
                row += r" \\"
                rows.append(row)
                rows_this_model += 1

        rows.append(r"\midrule")

    if rows:
        rows.pop()  # Remove trailing \midrule

    footer = r"""\bottomrule
\end{tabular}
\end{table*}
"""
    return header + "\n".join(rows) + "\n" + footer


def main():
    zeroshot_data = load_json(OUTPUT_DIR / "zeroshot_all_metrics.json")
    fewshot_data = load_json(OUTPUT_DIR / "fewshot_all_metrics.json")

    # Generate each table
    tables = {
        "table_i_zeroshot.tex": generate_table_i(zeroshot_data),
        "table_ii_scaling.tex": generate_table_ii(zeroshot_data, fewshot_data),
        "table_supp_fewshot.tex": generate_table_supp_fewshot(fewshot_data),
        "table_combined.tex": generate_combined_table(zeroshot_data, fewshot_data),
    }

    for filename, content in tables.items():
        output_path = TABLE_DIR / filename
        with open(output_path, "w") as f:
            f.write(content)
        print(f"Written: {output_path}")

    print("\nDone. Tables generated in outputs/tables/")


if __name__ == "__main__":
    main()
